apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  template:
    spec:
      containers:
      - name: app
        volumeMounts:
        - name: mysql-config
          mountPath: /config/mysql
      volumes:
      - name: mysql-config
        configMap:
          name: mysql-config
