apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- config.yaml
- app.yaml
patchesStrategicMerge:
# The mysql service has to be deployed separately for the binding convention to work
- binding.yaml
configMapGenerator:
  - name: env-config
    behavior: merge
    literals:
      - SPRING_CONFIG_LOCATION=classpath:/,file:///config/mysql/
